services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marine_vessels
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.docker
    volumes:
      - ./server/src:/server/src
      - ./shared:/server/shared

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    env_file:
      - .env.docker
    volumes:
      - ./client/src:/client/src
      - ./shared:/client/shared

volumes:
  postgres_data: